---
engines:
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
    exclude_fingerprints:
    - 6d18a19a385e71c70ea35085bc463f43
    - ccfcd077feb2d6820f935996636da8f3
  eslint:
    enabled: true
  fixme:
    enabled: false
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.rb"
exclude_paths:
- ".*"
