---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
    exclude_fingerprints:
      - e90f5ceaaaf6e613e221ffc4dd84fa37
      - 1fca042e9b232b8f28944f0c89d5f34c
  fixme:
    enabled: false
  rubocop:
    enabled: true
    channel: rubocop-0-62
ratings:
  paths:
  - "**.rb"
exclude_paths:
- ".*"
