---
engines:
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      exclude_paths:
      # Exclude spec/ from duplication engine since too dry specs
      # reduces readability.
      - spec/
  eslint:
    enabled: true
  fixme:
    enabled: false
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.rb"
exclude_paths:
- ".*"
