plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  DisplayCopNames: true
  NewCops: enable

RSpec/SpecFilePathFormat:
  Enabled: false

Style/Attr:
  Enabled: false

Style/AccessorGrouping:
  Exclude:
    - 'lib/fortnox/resources/**/*'
    - 'lib/fortnox/struct.rb'
    - 'spec/fortnox/struct_spec.rb'
    - 'spec/fortnox/resource_spec.rb'

Style/Documentation:
  Enabled: false

Style/WordArray:
  EnforcedStyle: brackets

Style/SymbolArray:
  EnforcedStyle: brackets

RSpec/MultipleMemoizedHelpers:
  Max: 6

RSpec/NestedGroups:
  Max: 5
