plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  DisplayCopNames: true
  NewCops: enable

RSpec/SpecFilePathFormat:
  Enabled: false

Style/Attr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/WordArray:
  EnforcedStyle: brackets

Style/SymbolArray:
  EnforcedStyle: brackets

RSpec/MultipleMemoizedHelpers:
  Max: 6

RSpec/NestedGroups:
  Max: 5

Naming/VariableNumber:
  AllowedIdentifiers:
    - request_1
    - request_2
