require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true

RSpec/FilePath:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false
  
Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Naming/PredicateName:
  Exclude:
    - 'spec/support/matchers/**/*'

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

Style/WordArray:
  EnforcedStyle: brackets

RSpec/MultipleMemoizedHelpers:
  Max: 7
