inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: true

RSpec/FilePath:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Max: 7

Lint/RaiseException:
  Enabled: false

Style/Documentation:
  Enabled: false
  
Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Naming/PredicateName:
  Exclude:
    - 'spec/support/matchers/**/*'
