# frozen_string_literal: true

require 'fortnox/api/types'

require 'fortnox/api/mappers/value/array'
require 'fortnox/api/mappers/value/country_string'
require 'fortnox/api/mappers/value/date'
require 'fortnox/api/mappers/value/hash'
require 'fortnox/api/mappers/value/identity'
require 'fortnox/api/mappers/customer'
require 'fortnox/api/mappers/default_delivery_types'
require 'fortnox/api/mappers/default_templates'
require 'fortnox/api/mappers/edi_information'
require 'fortnox/api/mappers/email_information'
require 'fortnox/api/mappers/invoice_row'
require 'fortnox/api/mappers/invoice'
require 'fortnox/api/mappers/order_row'
require 'fortnox/api/mappers/order'
require 'fortnox/api/mappers/project'
require 'fortnox/api/mappers/unit'
require 'fortnox/api/mappers/terms_of_payment'
